In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('superstore.csv')

In [3]:
df.head()

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,Number_of_Record,Order.Date,Order.ID,...,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,00:00.0,CA-2011-130813,...,19,Consumer,00:00.0,Second Class,4.37,California,Paper,2011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,00:00.0,CA-2011-148614,...,19,Consumer,00:00.0,Standard Class,0.94,California,Paper,2011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,00:00.0,CA-2011-118962,...,21,Consumer,00:00.0,Standard Class,1.81,California,Paper,2011,North America,32
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,00:00.0,CA-2011-118962,...,111,Consumer,00:00.0,Standard Class,4.59,California,Paper,2011,North America,32
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,1,00:00.0,CA-2011-146969,...,6,Consumer,00:00.0,Standard Class,1.32,California,Paper,2011,North America,40

In [4]:
df.shape

(51290, 27)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 27 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Category          51290 non-null  object
 1   City              51290 non-null  object
 2   Country           51290 non-null  object
 3   Customer.ID       51290 non-null  object
 4   Customer.Name     51290 non-null  object
 5   Discount          51290 non-null  float64
 6   Market            51290 non-null  object
 7   Number_of_Record  51290 non-null  int64
 8   Order.Date        51290 non-null  object
 9   Order.ID          51290 non-null  object
 10  Order.Priority    51290 non-null  object
 11  Product.ID        51290 non-null  object
 12  Product.Name      51290 non-null  object
 13  Profit            51290 non-null  float64
 14  Quantity          51290 non-null  int64
 15  Region            51290 non-null  object
 16  Row.ID            51290 non-null  int64
 17  Sales             51290 non-null  int64
 18  Segment           51290 non-null  object
 19  Ship.Date         51290 non-null  object
 20  Ship.Mode         51290 non-null  object
 21  Shipping.Cost     51290 non-null  float64
 22  State             51290 non-null  object
 23  Sub.Category      51290 non-null  object
 24  Year              51290 non-null  int64
 25  Market2           51290 non-null  object
 26  weeknum           51290 non-null  int64
dtypes: float64(3), int64(6), object(18)
memory usage: 10.6+ MB

In [6]:
df.columns

Index(['Category', 'City', 'Country', 'Customer.ID', 'Customer.Name',
       'Discount', 'Market', 'Number_of_Record', 'Order.Date', 'Order.ID',
       'Order.Priority', 'Product.ID', 'Product.Name', 'Profit', 'Quantity',
       'Region', 'Row.ID', 'Sales', 'Segment', 'Ship.Date', 'Ship.Mode',
       'Shipping.Cost', 'State', 'Sub.Category', 'Year', 'Market2', 'weeknum'],
      dtype='object')

In [7]:
df.isnull().sum()

Category            0
City                0
Country             0
Customer.ID         0
Customer.Name       0
Discount            0
Market              0
Number_of_Record    0
Order.Date          0
Order.ID            0
Order.Priority      0
Product.ID          0
Product.Name        0
Profit              0
Quantity            0
Region              0
Row.ID              0
Sales               0
Segment             0
Ship.Date           0
Ship.Mode           0
Shipping.Cost       0
State               0
Sub.Category        0
Year                0
Market2             0
weeknum             0
dtype: int64

No Missing Values in our Dataset

In [8]:
df.duplicated().sum()      #Checking Duplicate Values

np.int64(0)

There is no Duplicat Values

In [9]:
# Correct Datatype
df['Order.Date'] = pd.to_datetime(df['Order.Date'])
df['Ship.Date'] = pd.to_datetime(df['Ship.Date'])

In [10]:
df[['Order.Date', 'Ship.Date']].dtypes

Order.Date    datetime64[ns]
Ship.Date     datetime64[ns]
dtype: object

The dataset was inspected for missing values and duplicate records. No missing values or duplicates were found. Date columns (Order.Date and Ship.Date) were converted to datetime format for proper analysis. Numerical columns such as Sales and Profit were already in the correct format.

In [11]:
df['Sales'].sum()         #Total Sales

np.int64(12642905)

In [12]:
df['Profit'].sum()        #Total Profit

np.float64(1467457.2912800002)

In [13]:
top5_customers = (df.groupby('Customer.Name')['Sales'].sum().sort_values(ascending=False).head(5))
top5_customers

Customer.Name
Tom Ashbrook          40489
Tamara Chand          37453
Greg Tran             35552
Christopher Conant    35187
Sean Miller           35170
Name: Sales, dtype: int64

Top 5 Customer by Sales

In [14]:
df.groupby('Segment')[['Sales', 'Profit']].sum()     # Total Sales vs Total Profit

               Sales        Profit
Segment
Consumer     6508141  749239.78206
Corporate    3824808  441208.32866
Home Office  2309956  277009.18056